spring:
  profiles:
    active: stg

error:
  whitelabel:
    enabled: false

amazon:
  associate_id: kokomal

logging:
  level:
    root: INFO
    
management:
  server:  
    port: 8877
    servlet:
      context-path: /mgmt