server:
  port: 8443
  ssl:
    key-store: classpath:keys/keystore.p12
    key-store-password: letmein
    key-password: letmein
    key-store-type: PKCS12
  security:
    require-ssl: true
    alias: tomcat
    
logging:
  level:
    root: INFO
    org:
      hibernate: INFO
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    driverClassName: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql